name: BloodAlchemy
author: Mooy1
description: My entry for the 2021 Addon Jam
main: io.github.mooy1.bloodalchemy.BloodAlchemy
website: https://github.com/Mooy1/BloodAlchemy
depend: [Slimefun]
version: ${project.version}
api-version: 1.16

commands:
  bloodalchemy:
    description: Do /bloodalchemy help for a list of commands
    usage: /bloodalchemy <subcommand>
    aliases: [ba]
